### PR TITLE
Build vulkan support

### PR DESCRIPTION
**Pull request by catsout**

### CODE REVIEW

**Comment by catsout** [comment]
bot, build io.mpv.Mpv

**Comment by catsout** [comment]
bot, build io.mpv.Mpv

**Comment by dgcampea** [comment]
I'm not so sure about including _spirv-headers_ and _spirv-tools_ in the manifest file as they are already part of the Freedesktop SDK if I understand correctly. Did you try building without them?

**Comment by catsout** [comment]
> as they are already part of the Freedesktop SDK. Did you try building without them?

I didn't know this, but I think this can be difficult as the shaderc doesn't provide the method to build against system spirv packages.  
Maybe we can take a look at traditional package manager.

**Pull request merged**
