### PR TITLE
Update runtime to 24.08

### LINKED ISSUE #546: Update to freedesktop 24.08 runtime
The flatpak runtime could be updated from 23.08 to 24.08.

### PR DESCRIPTION
**Pull request by TomiOhl**
Resolves #546

### CODE REVIEW

**Comment by TomiOhl** [comment]
The last part of the logs: 
```
checking for sys/mount.h... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for libgcrypt-config... no
checking for LIBGCRYPT - version >= 1.6.0... no
checking for libgcrypt-config... no
checking for LIBGCRYPT - version >= 1.1.94... no
configure: error: libgcrypt not found on system
FB: host_command_exited_cb 1621930 256
]2;flatpak-builder: Cleanup libaacsError: module libaacs: Child process exited with code 1
FB: Unmounting read-only fs: fusermount -uz /srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/rofiles/rofiles-otLICP
program finished with exit code 1
```
From what I could find, in the 23.08 runtime libgcrypt was fixed at version 1.10. I find no evidence that it has been removed though 
But here is a similar issue: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1775

**Comment by Erick555** [comment]
libgcrypt is in runtime but upstream changed they way it should be detected. libaacs needs adjust for that.

**Comment by Erick555** [comment]
alternatively you may bundle older libgcrypt version for now.

also libv4l2, shaderc, glslang and SPIRV-* are all in runtime so you may drop them to reduce maintenance burden a bit.

**Comment by TomiOhl** [comment]
libaacs is version 0.11.1, which is also the latest version, so a simple update won't solve the issue if I'm correct. Can you suggest what exactly needs to be done in this case?

**Comment by Erick555** [comment]
you need to write a patch or find such patch somewhere in case someone else tackled this problem already. This may be the hard way so the easier way is to build libgrypt 1.10.3 (last one before libgcrypt-config was dropped) in manifest putting it just before libaacs.

**Comment by Erick555** [comment]
you can find example how to build it here, just use different version and hash: https://github.com/flathub/im.pidgin.Pidgin/blob/3eff7e13764d70dacbb4ce8a9a4eb7ea847c4e18/plugins/pidgin-otr.json#L38

**Comment by fastrizwaan** [comment]
https://github.com/flathub/io.mpv.Mpv/pull/548 merged.

**Pull request closed without merging**
