### PR TITLE
Fixes #148 Broken video after libplacebo upgrade

### LINKED ISSUE #148: Broken video after libplacebo upgrade
Commit https://github.com/flathub/io.mpv.Mpv/commit/4db9d0ce43d078563e47a37c56484834e763c625 breaks video playback.
The video is rendered as solid blue, with audio playing in the background.
Reverting to previous version with:
```sh
sudo flatpak update --commit=98c2098ac8fbf8169eb252f7dba028ff8c3aa361c6eccaba2f175a7eb1001afa io.mpv.Mpv
````
fixes this.

## Logs
```
[vo/gpu/libplacebo] shaderc output:
[vo/gpu/libplacebo] error:input: Unknown SPIR-V version 10600
[vo/gpu/libplacebo] shaderc compile status 'error' (1 errors, 0 warnings)
[vo/gpu/libplacebo] vk_compile_glsl(gpu, tmp, GLSL_SHADER_VERTEX, params->vertex_shader, &vert): VK_ERROR_INITIALIZATION_FAILED (../src/vulkan/gpu_pass.c:509)
[vo/gpu/libplacebo] vertex shader source:
```

### PR DESCRIPTION
**Pull request by kevinlekiller**
Updates libplacebo to latest version, this requires upgrading shaderc, which requires upgrading glslang.

Closes #148
Closes #150
Closes #151

### CODE REVIEW

**Comment by kevinlekiller** [comment]
Builds locally. Will investigate.

**Comment by kevinlekiller** [comment]
Well, it doesn't like something about the x-checker-data, so I'll leave it commented out, if you guys want to try to fix it, I'll let you, it's odd since locally it works.

**Comment by fastrizwaan** [comment]
i'm getting 
```
mpv: error while loading shared libraries: libSPIRV.so: cannot open shared object file: No such file or directory
```

**Comment by kevinlekiller** [comment]
I removed the cleanup and it works locally, will try pushing and see if the bot's build works.

**Comment by fastrizwaan** [comment]
Yes, it works! Thank you so much for fixing it.

**Comment by kevinlekiller** [comment]
No worries. Trying to update some of the sources now, will submit a PR if all works.

**Pull request merged**
