### PR TITLE
Update runtime version to 23.08 to and enable Vulkan video decode support

### PR DESCRIPTION
**Pull request by waruiji**

### CODE REVIEW

**Comment by fastrizwaan** [comment]
@waruiji please do not update to 23.08 because of mesa bug in 23.08 https://github.com/flathub/io.mpv.Mpv/pull/314#issuecomment-1808987854

**Comment by waruiji** [comment]
Then let's wait until it's resolved to get the required vulkan update.

**Comment by fastrizwaan** [comment]
@waruiji could you test https://github.com/flathub/io.mpv.Mpv/pull/363 (already merged)

**Comment by rago666** [comment]
@fastrizwaan I have tested it on my intel machine (Fedora kde wayland session). Both h264 & h265 works with vulkan decoding.
For anyone interested [this](https://github.com/mpv-player/mpv/issues/11739) is the guide to setting everything up.

**Comment by waruiji** [comment]
I can also confirm that everything works as expected. Thanks!

**Pull request closed without merging**
